server:
  servlet:
    context-path: /uaa
  port: 5000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: admin
    url: jdbc:mysql://st-db:3307/pb-service?serverTimezone=UTC
    platform: mysql
    initialization-mode: always
    continue-on-error: true
    port: 3307
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

    database: mysql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false;
    database-platform: org.hibernate.dialect.MySQL8Dialect
